[package]
name = "native_api_1c_core"
version = "0.1.0"
edition = "2021"

[dependencies]
utf16_lit = "2.0"
syn = { version = "2.0.28", features = ["full"] }
quote = "1.0.32"
native_api_1c_macro = { path = "../native_api_1c_macro" }
